import express from 'express';
import path from 'path';
import multer from 'multer';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from "@google/genai";
import PDFDocument from 'pdfkit';
import fs from 'fs';

const app = express();
const PORT = 3000;
const upload = multer({ storage: multer.memoryStorage() });

// Gemini Client Lazy Init
let genAI: any = null;
function getGemini() {
  if (!genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY is missing');
    }
    genAI = new GoogleGenAI({ 
      apiKey,
      httpOptions: { headers: { 'User-Agent': 'aistudio-build' } } 
    });
  }
  return genAI;
}

app.use(express.json());

// API: Predict Pneumonia using Gemini Vision
app.post('/api/predict', upload.single('image'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No image uploaded' });
    }

    const ai = getGemini();
    const model = 'gemini-3-flash-preview'; // Flash is great for visual tasks

    const imageBuffer = req.file.buffer;
    const base64Image = imageBuffer.toString('base64');

    const prompt = `
      You are an expert radiologist. Analyze this chest X-ray image for signs of Pneumonia.
      Return your analysis strictly in JSON format with the following keys:
      {
        "label": "NORMAL" or "PNEUMONIA",
        "confidence": a number between 0 and 1 representing your certainty,
        "reasoning": "A concise explanation of the visual markers you observed (e.g., opacities, lung clarity)",
        "clinicalNotes": "General medical advice or next steps following this observation"
      }
      If the image is not a chest X-ray, return "label": "INVALID".
    `;

    const result = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType: req.file.mimetype, data: base64Image } },
          { text: prompt }
        ]
      }
    });

    const responseText = result.text;
    // Extract JSON (Gemini might wrap it in markdown blocks)
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Failed to parse AI response');
    }

    const prediction = JSON.parse(jsonMatch[0]);

    if (prediction.label === 'INVALID') {
      return res.status(400).json({ error: 'Please upload a valid Chest X-Ray image.' });
    }

    res.json(prediction);
  } catch (error: any) {
    console.error('Prediction Error:', error);
    res.status(500).json({ error: error.message || 'Internal Server Error' });
  }
});

// API: Generate Medical Report PDF
app.post('/api/report', async (req, res) => {
  try {
    const { patientName, date, prediction } = req.body;

    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=PneumoGuard_Report_${patientName.replace(/\s+/g, '_')}.pdf`);

    doc.pipe(res);

    // Styling
    doc.fontSize(25).text('PneumoGuard AI - Medical Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Date: ${date}`);
    doc.text(`Patient Name: ${patientName}`);
    doc.moveDown();
    doc.fontSize(16).text('Analysis Results:', { underline: true });
    doc.moveDown();
    
    doc.fontSize(14).fillColor(prediction.label === 'PNEUMONIA' ? 'red' : 'green')
       .text(`Diagnosis: ${prediction.label}`);
    doc.fillColor('black').fontSize(12).text(`Confidence Score: ${(prediction.confidence * 100).toFixed(2)}%`);
    
    doc.moveDown();
    doc.fontSize(14).text('Radiologist Observations (AI-Generated):');
    doc.fontSize(12).text(prediction.reasoning);
    
    doc.moveDown();
    doc.fontSize(14).text('Clinical Notes:');
    doc.fontSize(12).text(prediction.clinicalNotes);

    doc.moveDown(2);
    doc.fontSize(10).fillColor('gray').text('Disclaimer: This report is generated by an AI system (PneumoGuard AI) for educational and preliminary screening purposes. It should not be treated as a final medical diagnosis. Please consult a qualified radiologist.', { align: 'justify' });

    doc.end();
  } catch (error: any) {
    console.error('Report Generation Error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// Vite Middleware Integration
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
